version: "2"

run:
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - staticcheck
  disable:
    - govet

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - gci

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude:
    - "bad syntax for struct tag key"
    - "bad syntax for struct tag pair"