version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

# DDQP is a library, so we skip binary builds
builds:
  - skip: true

# GitHub Releases configuration
release:
  github:
    owner: jonwinton
    name: ddqp
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## DDQP v{{.Version}}

    Release of the DataDog Query Parser library.

    ### Installation

    ```bash
    go get github.com/jonwinton/ddqp@{{.Tag}}
    ```

# Changelog configuration - delegates to git-cliff
changelog:
  disable: true

# Skip archives for library releases (users will use go get)
archives:
  - id: skip-archives
    meta: true

# Announce the release (optional - can be configured later)
announce:
  skip: false

# Metadata
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

# Git configuration
git:
  ignore_tags:
    - "*-rc*"
    - "*-beta*"
    - "*-alpha*"
